=== jaranovy/FileProcessor/TestingData/FileProcessorConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="FileProcessor"
    xmlns="http://novych.cz/schemas/Schemas/FileProcessorConfig"
    targetNamespace="http://novych.cz/schemas/Schemas/FileProcessorConfig"
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="FileProcessorConfig">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="Task" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="Files">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="File" minOccurs="0" maxOccurs="unbounded">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="256" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                    <xs:element name="FileMask" minOccurs="0" maxOccurs="unbounded">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="256" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="Actions">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="Action" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>

                          <xs:element name="Type" minOccurs="1" maxOccurs="1">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:maxLength value="256" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>

                          <xs:element name="TableName" minOccurs="0" maxOccurs="1">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:maxLength value="256" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>

                          <xs:element name="Query" minOccurs="0" maxOccurs="1">
                            <xs:simpleType>
                              <xs:restriction base="xs:string"/>
                            </xs:simpleType>
                          </xs:element>

                          <xs:element name="Destination" minOccurs="0" maxOccurs="1">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:maxLength value="256" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>

                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== jaranovy/FileProcessor/TestingData/Objednavky.xml
<?xml version="1.0" encoding="utf-8" ?>
<FileProcessorConfig xmlns="http://novych.cz/schemas/Schemas/FileProcessorConfig"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://novych.cz/schemas/Schemas/FileProcessorConfig FileProcessorConfig.xsd">
  <Task>
    <Files>
      <File>..\..\..\TestingData\Objednavky.csv</File>
    </Files>
    <Actions>
      <Action>
        <Type>Archive</Type>
        <Destination>.\TestingData\Backup\</Destination>
      </Action>
      <Action>
        <Type>ProcessRecord</Type>
        <Query>UPDATE [Dbo].[Zbozi] SET [pocet_objednanych_kusu] = pocet_objednavanych_kusu WHERE [ID] = ID_zbozi</Query>
      </Action>
      <Action>
        <Type>Export</Type>
        <Query>SELECT [ID], [nazev], ([pocet_kusu_skladem] - [pocet_objednanych_kusu]) as [pocet_expedovanych_kusu] from [Dbo].[Zbozi] ORDER BY [ID];</Query>
        <Destination>.\TestingData\Vyrizeno.csv</Destination>
      </Action>
    </Actions>
  </Task>
</FileProcessorConfig>
