=== jaranovy/FileProcessor/FileProcessor/TestingData/FileProcessorConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="FileProcessor"
    xmlns="http://novych.cz/schemas/Schemas/FileProcessorConfig"
    targetNamespace="http://novych.cz/schemas/Schemas/FileProcessorConfig"
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="FileProcessorConfig">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="Task">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="Files">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="File" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="256" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                    <xs:element name="FileMask" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="256" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>


              <xs:element name="Actions">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="Archive" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>

                          <xs:element name="Destination">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:maxLength value="256" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>

                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>


                    <xs:element name="LoadFile" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>

                          <xs:element name="TableName">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:maxLength value="256" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>

                          <xs:element name="Query">
                            <xs:simpleType>
                              <xs:restriction base="xs:string"/>
                            </xs:simpleType>
                          </xs:element>

                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>


                    <xs:element name="ProcessRecord" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>

                          <xs:element name="Query">
                            <xs:simpleType>
                              <xs:restriction base="xs:string"/>
                            </xs:simpleType>
                          </xs:element>

                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>


                    <xs:element name="Export" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>

                          <xs:element name="Query">
                            <xs:simpleType>
                              <xs:restriction base="xs:string"/>
                            </xs:simpleType>
                          </xs:element>

                          <xs:element name="Destination">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:maxLength value="256" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>

                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== jaranovy/FileProcessor/FileProcessor/TestingData/PrijemZbozi.xml
<?xml version="1.0" encoding="utf-8" ?>
<FileProcessorConfig xmlns="http://novych.cz/schemas/Schemas/FileProcessorConfig"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://novych.cz/schemas/Schemas/FileProcessorConfig FileProcessorConfig.xsd">
  <Task>
    <Files>
      <File>.\TestingData\PrijemZbozi.csv</File>
    </Files>
    <Actions>
      <Archive>
        <Destination>.\TestingData\Backup\</Destination>
      </Archive>
      <ProcessRecord>
        <Query>update zbozi set pocet_dostupnych_kusu = pocet_dostupnych_kusu + pocet_prijatych_kusu where id = ID_zbozi</Query>
      </ProcessRecord>
      <Export>
        <Query>select id, nazev, pocet_dostupnych_kusu from zbozi order by id</Query>
        <Destination>.\TestingData\PrijatoZbozi.csv</Destination>
      </Export>
    </Actions>
  </Task>
</FileProcessorConfig>
